[profile.release]
strip = "symbols"
panic = "abort"

[target.aarch64-unknown-linux-musl]
# see https://github.com/fermyon/spin/pull/2307/files#diff-f6009bd0d260464389ace37ab2f89adae993e1fa4a47f779e4c9859937005ced
rustflags = ["-C", "target-feature=+fp16", "-C", "target-feature=+crt-static", "-C", "link-self-contained=yes"]

[target.x86_64-unknown-linux-musl]
# see https://github.com/fermyon/spin/pull/2307/files#diff-f6009bd0d260464389ace37ab2f89adae993e1fa4a47f779e4c9859937005ced
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-self-contained=yes"]