spin_manifest_version = 2

[application]
name = "spin-multi-trigger-app"
version = "0.1.0"
authors = ["Rajat Jindal <rajatjindal83@gmail.com>"]
description = ""

[variables]
redis_address = { required = true }
redis_channel = { required = true }

[[trigger.http]]
route = "/..."
component = "spin-http-trigger"

[component.spin-http-trigger]
source = "spin-http-trigger/target/wasm32-wasip1/release/spin_http_trigger.wasm"
allowed_outbound_hosts = []
[component.spin-http-trigger.build]
command = "cargo build --target wasm32-wasip1 --release --manifest-path spin-http-trigger/Cargo.toml"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.redis]]
channel = "{{ redis_channel }}"
address = "{{ redis_address }}"
component = "spin-redis-trigger"

[component.spin-redis-trigger]
source = "spin-redis-trigger/target/wasm32-wasip1/release/spin_redis_trigger.wasm"
allowed_outbound_hosts = ["redis://*:*"]

[component.spin-redis-trigger.variables]
redis_address = "{{ redis_address }}"

[component.spin-redis-trigger.build]
command = "cargo build --target wasm32-wasip1 --release --manifest-path spin-redis-trigger/Cargo.toml"